run_glucose_sweep_core( ...
    'sigmaMode', 'parametrized_totalweight', ...
    'modeLabel', 'Parametrized', ...
    'rawFolderName', 'glucose_sweep_parametrized', ...
    'outputFolderName', 'Parametrized', ...
    'fluxFileName', 'data_modelV0_kcatscomb_Parametrized.csv', ...
    'sectorsFileName', 'sectors_modelV0_kcatscomb_Parametrized.csv', ...
    'aceFileName', 'aceTData_modelV0_kcatscomb_Parametrized.csv', ...
    'summaryNote', 'Parametrized glucose sweep', ...
    'alearn', 0.001);
