run_glucose_sweep_core( ...
    'sigmaMode', 'homogeneous', ...
    'modeLabel', 'Homogeneous', ...
    'rawFolderName', 'glucose_sweep_homogeneous', ...
    'outputFolderName', 'iML1515_Homogeneous', ...
    'fluxFileName', 'dataFlux_Homogeneous.csv', ...
    'sectorsFileName', 'sectors_Homogeneous.csv', ...
    'aceFileName', 'aceT_Homogeneous.csv', ...
    'summaryNote', 'Homogeneous glucose sweep', ...
    'alearn', 0.001);
